---
- name: set up webserver
  hosts: all
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
        update_cache: yes  # optional but recommended
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes  # if you want to also enable nginx
